import * as peggy from 'peggy'
import * as fs from 'fs'
import { fileURLToPath } from 'node:url'
import type { Script, SourceLocation } from '../types.js'
import { DiagnosticNote, LocationRange, Stage } from 'peggy'

// ─── Parser bootstrap ─────────────────────────────────────────────────────────
//
// Strategy (in priority order):
//   1. Import the pre-compiled parser generated by `npm run generate-parser`.
//      This is a static ES module — zero runtime compilation cost.
//   2. Fall back to compiling the .pegjs grammar source on the fly via peggy.
//      Used during development before the first build, or in test environments
//      where the pre-compiled file is not present.
//
// Prettier's Parser.parse() must be synchronous, so we resolve the parser
// eagerly at module initialisation time using a top-level await (valid in ESM).

interface CompiledParser {
  parse(input: string, options?: Record<string, unknown>): unknown
}

// Top-level await: resolves once at import time, before any parse() call.
const _parser: CompiledParser = await (async (): Promise<CompiledParser> => {
  try {
    // sieve-parser.js is generated by: peggy --format es -o src/parser/generated/sieve-parser.js src/parser/sieve.pegjs
    // At runtime this resolves to dist/parser/generated/sieve-parser.js (after build).
    const precompiled = await import('./generated/sieve-parser.js')
    return { parse: precompiled.parse }
  } catch {
    // Pre-compiled parser not available — compile from grammar source.
    const grammarPath = fileURLToPath(new URL('./sieve.pegjs', import.meta.url))
    const grammar = fs.readFileSync(grammarPath, 'utf8')
    const compiled = peggy.generate(grammar, {
      output: 'parser',
      error(stage: Stage, message: string, location?: LocationRange, notes?: DiagnosticNote[]) {
        throw new Error(
          `[prettier-plugin-sieve] Grammar error at ${String(stage)}: ${message} ${JSON.stringify(location)} ${JSON.stringify(notes)}`
        )
      },
    })
    return compiled as unknown as CompiledParser
  }
})()

export function parse(text: string): Script {
  try {
    return _parser.parse(text, { grammarSource: '<sieve>' }) as Script
  } catch (err: unknown) {
    if (err instanceof Error) throw err
    throw new Error(String(err), { cause: err })
  }
}

export function locStart(node: { loc?: SourceLocation }): number {
  return node.loc?.start.offset ?? 0
}

export function locEnd(node: { loc?: SourceLocation }): number {
  return node.loc?.end.offset ?? 0
}
